markdown-links-verificator:
  image: gitlab-registry.rz.tu-ilmenau.de/fakmb/qbv/topics/docker/tools/markdown-links-verificator:2021-03-15
  script: markdown-links-verificator

# build x86_64 Windows
build-windows:
  image: gitlab-registry.rz.tu-ilmenau.de/fakmb/qbv/topics/docker/mingw/mingw:2022-06-22
  script: script/build.sh

# build x86_64 Linux
build-linux:
  image: gitlab-registry.rz.tu-ilmenau.de/fakmb/qbv/topics/docker/gcc/gcc:2022-06-22
  script: script/build.sh
